language: java
env:
  - TEST_DIR=CoarseGrainedImproved
  - TEST_DIR=CoarseGrained
  - TEST_DIR=FineGrained
  - TEST_DIR=FineGrainedImproved
  - TEST_DIR=LockFree
  - TEST_DIR=LockFreeImproved
before_install: true
install: true
before_build:
  - jdk_switcher use oraclejdk8
build: 
  - cd coarseGrained && make
  - cd $TEST_DIR && make
before_script: 
  - jdk_switcher use oraclejdk8
script:
  - cd $TEST_DIR && make test
