language: java
env:
  - TEST_DIR=coarseGrained_updateImproved
  - TEST_DIR=coarseGrained_updated
  - TEST_DIR=fineGrained
  - TEST_DIR=fineGrainedImproved
  - TEST_DIR=lockFree
  - TEST_DIR=lockFreeImproved
before_install: true
install: true
before_build:
  - jdk_switcher use oraclejdk8
build: 
  - cd coarseGrained && make
  - cd $TEST_DIR && make
before_script: 
  - jdk_switcher use oraclejdk8
script:
  - cd $TEST_DIR && make test
